name: Docker-in-Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      docker:
        image: docker:20.10-dind
        options: >-
          --privileged
          --env DOCKER_TLS_CERTDIR=""
        ports:
          - 2375:2375

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker host
        run: echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Debug Docker version
        run: docker version

      - name: Build Inner Dockerfile
        run: |
          echo "🚀 Building inner Dockerfile"
          docker build -f inner.Dockerfile -t my-inner-image .

      # Optional: Run and test the image
      # - name: Run Container
      #   run: |
      #     docker run --rm my-inner-image
